Add patch for OpenSSL 3.2 compat
conda-forge/postgresql-feedstock pull request #192
Opened 2023-12-05 12:54 UTC by akrherz

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

When I created this patch in #181 for OpenSSL 3.2 compatibility, I failed to active it for use. :shrug:

2023-12-05 12:54 UTC, akrherz commented
@conda-forge-admin please rerender

2023-12-05 12:58 UTC, h-vetinari requested changes
See https://github.com/conda-forge/postgresql-feedstock/issues/191#issuecomment-1840744397

2023-12-05 14:26 UTC, akrherz commented
@h-vetinari I've never attempted publishing to a non-default channel.  Do I also need to target this PR at a new branch or is what I did correct?  Sorry :(

2023-12-05 23:18 UTC, h-vetinari commented
No need to apologise. We still need to mark the builds as broken first (PR to https://github.com/conda-forge/admin-requests), then rebuild this feedstock with `openssl <3.2` (to get some working builds, especially for the libxml2 migration). Your help on both of these would be appreciated.

Once that's done, we can publish this PR to a separate label, which is just a matter of adding `channel_targets:` in `conda_build_config.yaml` and then rerendering. Here's an [example](https://github.com/conda-forge/clangdev-feedstock/blob/a72d48bfa11756ee445beacd4c871e73cf45d7cd/recipe/conda_build_config.yaml#L25-L26).

2023-12-06 02:27 UTC, akrherz commented
Thanks @h-vetinari , I think I did what you asked with 641c9cd above then?

I'll work on the intermediate build so to get an openssl 3.1.4 + libxml2 2.12 solvable combo

2023-12-06 03:07 UTC, akrherz commented
@conda-forge-admin  please rerender

2023-12-06 21:14 UTC, akrherz commented
@conda-forge/postgresql This PR should be ready for review.

2023-12-06 22:18 UTC, hmaarrfk commented on recipe/conda_build_config.yaml
> +  - conda-forge postgres_dev
is this ready to be reverted?

2023-12-07 00:42 UTC, akrherz commented
> The upload channel should be revised.

What are you suggesting it should be revised to?  I thought I was using the suggestion here https://github.com/conda-forge/postgresql-feedstock/issues/191#issuecomment-1840744397

2023-12-07 01:41 UTC, akrherz commented
@conda-forge-admin please rerender

Augh, I give up :( 

```
$ mamba create -n dev openssl=3.2 libpq=16
openssl                 3.2.0  hd590300_1
libpq                    16.1  hedfdc17_5
```

2023-12-07 02:23 UTC, merged